joint_limit_repulsion.enabled: false
joint_limit_repulsion.max_torque: 5.0
joint_limit_repulsion.safe_range: 0.1

limit_error: true
limit_torques: true

log.enabled: false

max_delta_tau: 0.5

nullspace.damping: -1.0
nullspace.max_tau: 5.0
nullspace.projector_type: none
nullspace.regularization: 1.0e-06
nullspace.stiffness: 0.0

operational_space_regularization: 1.0
stop_commands: false

task.d_pos_x: -1.0
task.d_pos_y: -1.0
task.d_pos_z: -1.0
task.d_rot_x: -1.0
task.d_rot_y: -1.0
task.d_rot_z: -1.0

task.error_clip.rx: 0.5
task.error_clip.ry: 0.5
task.error_clip.rz: 0.5
task.error_clip.x: 0.05
task.error_clip.y: 0.05
task.error_clip.z: 0.05

task.k_pos_x: 0.0
task.k_pos_y: 0.0
task.k_pos_z: 0.0
task.k_rot_x: 0.0
task.k_rot_y: 0.0
task.k_rot_z: 0.0

use_coriolis_compensation: true
use_friction: false

use_gravity_compensation: true
use_local_jacobian: true

use_operational_space: false


